apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: exam-violanguyen
  labels:
    # Replace this by your own name
    createdBy: "Viola-Nguyen"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: nathansegers/big_data_and_ai-24_may_api
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 80
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: NAME
              value: "Viola Nguyen"
            - name: DATE
              value: "08-05-2024"

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
